### ISSUE TITLE
POST Request

### ISSUE THREAD

**Issue by lmsix** [KoichiHaradaEndor/HTTPServer#12]
Hello,

I have used your component and found an issue with the POST Command.
If one use the POST command with a body {"value"=1"} as follow : http://mysite.com/mykey=123
In the request object the body field will containt {"value"=1"}  and the query field will containt {"value"=1"}  where it should containt mykey=123.

The problem comes from the method RQ_parseWebVaraibles which uses the  WEB GET VARIABLES command.
If the http request is a GET no problem, if the request is a POST or a PUT  the  WEB GET VARIABLES command will give you the body of the request not the query (class request line n° (170) -> This.query:=RQ_parseWebVariables()

Best Regards,
Luc-Michel Six

**Comment by KoichiHaradaEndor** [comment]
Hello Luc,

Thanks for the report. I will take a look into it.

Best regards,
Koichi

**Comment by KoichiHaradaEndor** [comment]
Hi Luc,

I've corrected the issue. Please take a look when you have time.
When the HTTP method is other than GET, query string is now parsed manually (not using WEB GET VARIABLES).
If you find any issue on it, please let me know.

Again thanks for your contribution by reporting the problem.

Koichi

**Comment by lmsix** [comment]
Hello Koichi,

Thank you very much for your corrections.

Best Regards,
Luc-Michel

Le mar. 26 sept. 2023 à 15:06, HARADA Koichi ***@***.***> a
écrit :
